In [13]:
import pandas as pd
from pandas import Series, DataFrame
obj = Series([4,7,-5,3])
print (obj.values)
print (obj.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [15]:
obj2 = Series([4,7,-5,3],index = ['d','b','a','d'])
obj2

d    4
b    7
a   -5
d    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'v'], dtype='object')

In [14]:
obj2['a']

-5

In [31]:
obj2['d'] = 3
obj2

d    3
b    7
a   -5
d    3
dtype: int64

In [33]:
obj2[obj2>2]

d    3
b    7
d    3
dtype: int64

In [34]:
import numpy as np
np.exp(obj2)

d      20.085537
b    1096.633158
a       0.006738
d      20.085537
dtype: float64

In [35]:
'b' in obj2

True

In [37]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
sdata

{'Ohio': 35000, 'Oregon': 16000, 'Texas': 71000, 'Utah': 5000}

In [40]:
obj3 = Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [46]:
states = ['California','Ohio','Oregon','Texas']
obj4 = Series(sdata, index = states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [47]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [48]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [50]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [51]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [54]:
obj4.name = 'population'
obj4.index.name = 'index'
obj4

index
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [55]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [56]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [62]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
       'year':[2000,2001,2002,2001,2002],
       'pop':[1.5,1.7,3.6,2.4,2.9]}
frame = DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [63]:
DataFrame(data, columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [65]:
frame2 = DataFrame(data, columns = ['year','state','pop','debt'],
                  index = ['one','two','three','four','five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [68]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [70]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [74]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [78]:
frame2['debt'] = np.arange(5)
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [81]:
val = Series([-1.2,-1.5,-1.7], index= ['two','four','five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [89]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [90]:
del frame2['eastern']

In [91]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [93]:
pop = {'Nevada':{2001:2.4,2002:2.9},
      'Ohio':{2000:1.5, 2001:1.7,2002:3.6}}

In [96]:
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [97]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [103]:
pdata = {'Ohio':frame3['Ohio'][:-1],
        'Nevada':frame3['Nevada'][:2]}
DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [106]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [107]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [109]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])