In [2]:
from numpy import *
a = arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [7]:
import numpy as np
Z = np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [12]:
Z = np.arange(10,50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [15]:
z = np.arange(50)
z = z[::-1]
z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [17]:
z = ([1,2,0,0,4,0])
nz = np.nonzero(z)
nz

(array([0, 1, 4]),)

In [21]:
z = np.random.random((10,10))
print (z)
Zmin, Zmax = Z.min(), Z.max()

Zmin, Zmax

[[0.94651183 0.33961405 0.29457862 0.51741282 0.02880822 0.70397217
  0.78471066 0.3823573  0.98905551 0.01923724]
 [0.0671115  0.1244425  0.70179258 0.07411683 0.09226888 0.37361652
  0.46051453 0.89572533 0.40086192 0.34690412]
 [0.97729014 0.77461916 0.12335367 0.03820588 0.20122827 0.81331894
  0.81659239 0.73943764 0.83865349 0.70440789]
 [0.24255111 0.24154469 0.01788192 0.45077691 0.92242659 0.14273568
  0.10823968 0.95815814 0.96629307 0.43755672]
 [0.49826521 0.98003982 0.23004842 0.3697558  0.63513606 0.32258639
  0.06221771 0.67793238 0.15239872 0.02187736]
 [0.07920475 0.00301989 0.23107829 0.27330755 0.69888336 0.42806686
  0.00686602 0.76517009 0.94439167 0.76439387]
 [0.01447639 0.18952068 0.17560232 0.3959262  0.44250025 0.23311553
  0.32550382 0.11280868 0.5134525  0.65757427]
 [0.51939658 0.08009347 0.75088943 0.88402247 0.59626111 0.78176778
  0.91088111 0.02601052 0.96280821 0.22676436]
 [0.97720279 0.06360808 0.93533876 0.99174056 0.02371189 0.96956515
  0.26921569

(10, 49)

In [23]:
Z = np.random.random(30)
m = Z.mean()
m

0.5272303688380771

In [29]:
z = np.ones((5,5))
z = np.pad(z, pad_width = 1, mode = 'constant', constant_values = 2)
z

array([[2., 2., 2., 2., 2., 2., 2.],
       [2., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 2.],
       [2., 1., 1., 1., 1., 1., 2.],
       [2., 2., 2., 2., 2., 2., 2.]])

In [30]:
np.nan

nan

In [31]:
0 * np.nan

nan

In [32]:
np.nan == np.nan

False

In [33]:
np.inf

inf

In [35]:
np.nan - np.nan

nan

In [36]:
0.3 == 3 * 0.1

False

In [50]:
z = np.arange(3)
z

array([0, 1, 2])

In [56]:
z = np.diag(np.arange(4), k=-1)
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0]])

In [64]:
z = np.zeros((8,8),dtype = int)
z[1::2,::2] = 1
z[::2,1::2] = 1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [65]:
print (np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [66]:
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [70]:
z = np.random.random((5,5))
zmax,zmin = z.max(),z.min()
print (zmax,zmin)
z = (z-zmin)/(zmax-zmin)
z

0.9993151388756997 0.004023320302438571


array([[0.41422378, 0.06350383, 1.        , 0.52561219, 0.27806452],
       [0.14308735, 0.23405479, 0.59872189, 0.27349577, 0.25884493],
       [0.84749954, 0.37445277, 0.57415695, 0.7629889 , 0.95974668],
       [0.79656796, 0.45756055, 0.33505027, 0.24435017, 0.38794601],
       [0.78880953, 0.20412978, 0.52750629, 0.        , 0.24701383]])

In [75]:
z = np.dot(np.ones((5,3)),np.ones((3,2)))
z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [82]:
z = np.arange(11)
print (z)
z[(3<=z) & (z<=8)] *= -1
print (z)


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [88]:
print (sum(range(5),-1))
print (list(range(5)))

10
[0, 1, 2, 3, 4]


In [104]:
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print (z1,z2)
print (np.intersect1d(z1,z2))

[3 7 2 3 4 6 2 4 2 4] [6 7 4 3 0 8 4 9 6 7]
[3 4 6 7]


In [109]:
z = np.arange('2016-07','2016-08',dtype = 'datetime64[D]')
z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [115]:
z = np.random.uniform(0,10,10)
#z = z - z%1
print (np.floor(z))

[7. 6. 3. 8. 2. 2. 3. 6. 4. 2.]


In [118]:
z = np.zeros((5,5))
print (z)
print (np.arange(5))
z += np.arange(5)
z

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[0 1 2 3 4]


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [126]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print (equal)

False


In [134]:
z = np.random.random(10)
z[z.argmax()] = 0
z

array([0.72246402, 0.25658457, 0.04429808, 0.93698487, 0.77961205,
       0.208896  , 0.48624753, 0.73301484, 0.49210794, 0.        ])

In [147]:
z = np.random.random((10,2))
X, Y = z[:,0],z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
T

array([1.25675244, 0.80748018, 0.87089737, 0.5878436 , 1.41442607,
       1.3732395 , 0.96753009, 0.64055728, 0.04359861, 0.06076348])

In [150]:
z = np.zeros((5,5),[('x',float),('y',float)])
print (z)
z['x'],z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
z

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]


array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

In [153]:
for dtype in [np.int8,np.int32,np.int64]:
    print (np.iinfo(dtype).min)
    print (np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [154]:
for dtype in [np.float32, np.float64]:
    print (np.finfo(dtype).min)
    print (np.finfo(dtype).max)
    print (np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [159]:
print (np.set_printoptions(threshold = np.nan))

None


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [166]:
z = np.arange(100)
print (z)
v = np.random.uniform(0,100)
index = (np.abs(z-v)).argmin()
print (index,z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
39 39


In [173]:
z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
    print (index,value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [177]:
n = 10
p = 3
z = np.zeros((n,n))
np.put(z, np.random.choice(range(n*n),p,replace = False),1)
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [179]:
x = np.random.rand(5,10)
y = x - x.mean(axis = 1, keepdims = True)
y

array([[-1.38570562e-01,  8.98049784e-02,  2.30923901e-01,
        -7.86008071e-02,  6.75829330e-05, -2.34464003e-01,
         3.57001868e-01,  9.18665098e-02, -5.53135077e-02,
        -2.62715961e-01],
       [-1.40171301e-01, -9.44694755e-02, -3.48971208e-01,
         3.04414770e-01,  4.70208856e-01,  4.56552887e-01,
        -2.42029792e-01, -2.46707653e-01,  8.35659350e-02,
        -2.42393019e-01],
       [ 1.44279166e-01, -5.03739420e-03,  9.55195277e-02,
         1.13478636e-01,  2.89737530e-01, -3.92817800e-01,
         1.25221128e-01, -3.14222607e-01,  1.31882887e-01,
        -1.88041074e-01],
       [-9.37528146e-02,  2.88367184e-01,  3.83133065e-01,
         3.00068671e-01, -2.53163242e-01, -3.44069035e-01,
         2.93035352e-01, -3.59328552e-01,  2.02002525e-02,
        -2.34490880e-01],
       [-4.07820283e-01,  5.86054708e-02,  3.45075036e-01,
         2.36376008e-01,  2.88112234e-02,  1.47429939e-01,
         1.28790745e-01, -3.16776493e-01,  1.00304227e-01,
        -3.

In [188]:
z = np.random.randint(0,10,(3,3))
print (z)
print (z[z[:,2].argsort()])

[[7 6 4]
 [5 0 2]
 [6 2 6]]
[[5 0 2]
 [7 6 4]
 [6 2 6]]


In [190]:
z = np.random.randint(0,3,(3,10))
print ((~z.any(axis = 0).any()))

False


In [191]:
x = [1,2,3,4,5,6]
i = [1,3,9,3,4,1]
F = np.bincount(i,x)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [199]:
a = np.random.randint(0,10,(1,2,3,4))
a

array([[[[0, 8, 9, 9],
         [3, 6, 8, 7],
         [3, 3, 7, 9]],

        [[4, 5, 6, 8],
         [9, 4, 9, 4],
         [2, 0, 9, 3]]]])

In [201]:
a = np.random.uniform(0,1,(5,5))
b = np.random.uniform(0,1,(5,5))
np.diag(np.dot(a,b))

array([1.11262839, 1.69416294, 1.3117973 , 1.55737052, 1.51309044])

In [203]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
A

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [211]:
z = np.random.uniform(0,1,(10,10))
U,S,V = np.linalg.svd(z)
rank = np.sum(S > 1e-9)
rank

10

In [214]:
z = np.random.randint(0,10,50)
print (z)
print (np.bincount(z).argmax())

[7 9 4 1 2 7 0 6 2 1 2 2 0 7 5 6 2 6 0 7 6 4 4 2 2 3 7 2 5 9 7 0 2 1 6 6 5
 0 0 7 2 1 9 7 0 6 0 8 2 5]
2
